#!/bin/bash
# extract_patches.sh — Extract patches and new files from a patched Linux kernel
#
# This script compares a patched kernel against the vanilla kernel and generates:
#   - files/     : New files that don't exist in vanilla kernel
#   - patches/   : Unified diff patches for modified files
#
# Can be run from any directory — all paths are relative to 32-Kernel/.
#
# Usage: ./scripts/extract_patches.sh [patched_kernel_dir]
#
# Environment variables:
#   OUTPUT_FILES    - Output directory for new files (default: files)
#   OUTPUT_PATCHES  - Output directory for patches (default: patches)
#
# J. Nilo - December 2025

set -e

# Force C locale for consistent output parsing
export LC_ALL=C

# Configuration
KERNEL_VERSION="5.10.246"
KERNEL_MAJOR="5.x"
KERNEL_TARBALL="linux-${KERNEL_VERSION}.tar.xz"
KERNEL_URL="https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_MAJOR}/${KERNEL_TARBALL}"
VANILLA_DIR="linux-${KERNEL_VERSION}"
PATCHED_DIR_DEFAULT="linux-${KERNEL_VERSION}-rtl8196e"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KERNEL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "$KERNEL_DIR"

# Parse arguments
PATCHED_DIR="${1:-$PATCHED_DIR_DEFAULT}"

if [ ! -d "$PATCHED_DIR" ]; then
    echo -e "${RED}Error: Patched kernel directory not found: $PATCHED_DIR${NC}"
    echo "Usage: $0 [patched_kernel_dir]"
    echo ""
    echo "Default: $PATCHED_DIR_DEFAULT"
    exit 1
fi

PATCHED_DIR="$(cd "$PATCHED_DIR" && pwd)"

OUTPUT_FILES="${OUTPUT_FILES:-files}"
OUTPUT_PATCHES="${OUTPUT_PATCHES:-patches}"

echo "==================================================================="
echo "  Extract patches from Linux ${KERNEL_VERSION}"
echo "==================================================================="
echo ""
echo "Patched kernel: $PATCHED_DIR"
echo "Vanilla kernel: $VANILLA_DIR"
echo "Output will be in: ${OUTPUT_FILES}/ and ${OUTPUT_PATCHES}/"
echo ""

# Check if output dirs exist and warn
if [ -d "$OUTPUT_FILES" ] || [ -d "$OUTPUT_PATCHES" ]; then
    echo -e "${YELLOW}WARNING: ${OUTPUT_FILES}/ and/or ${OUTPUT_PATCHES}/ directories exist and will be overwritten!${NC}"
    read -p "Continue? (y/n) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Download and extract vanilla kernel
if [ ! -f "$KERNEL_TARBALL" ]; then
    echo -e "${YELLOW}Downloading vanilla Linux ${KERNEL_VERSION}...${NC}"
    wget -q --show-progress "$KERNEL_URL"
fi
echo -e "${YELLOW}Extracting vanilla kernel...${NC}"
rm -rf "$VANILLA_DIR"
tar xf "$KERNEL_TARBALL"
echo ""

# Create output directories
rm -rf "$OUTPUT_FILES" "$OUTPUT_PATCHES"
mkdir -p "$OUTPUT_FILES" "$OUTPUT_PATCHES"

echo -e "${YELLOW}Comparing patched kernel with vanilla...${NC}"
echo ""

# Function to check if file should be skipped (build artifacts, generated files)
should_skip() {
    local file="$1"

    case "$file" in
        # Build artifacts
        *.o|*.ko|*.mod|*.mod.c|*.a|*.cmd|*.dtb|*.rej|*.orig|*.tmp)
            return 0 ;;
        .*.cmd|.*.d)
            return 0 ;;
        System.map|vmlinux|vmlinux.*|modules.*)
            return 0 ;;
        */built-in.a|*/modules.order|*/Module.symvers)
            return 0 ;;
        */.config|*/.config.old|*/.version)
            return 0 ;;
        # Generated lex/yacc files
        *.lex.c|*.tab.c|*.tab.h)
            return 0 ;;
        # Generated by kbuild
        scripts/mod/devicetable-offsets.*|scripts/mod/elfconfig.h)
            return 0 ;;
        arch/mips/boot/compressed/bswapsi.c)
            return 0 ;;
        # Kernel generated files
        kernel/config_data*|lib/crc32table.h)
            return 0 ;;
    esac

    # Skip hidden files
    local basename=$(basename "$file")
    if [[ "$basename" =~ ^\. ]]; then
        return 0
    fi

    return 1
}

# Save diff output to temp file for processing
DIFF_OUTPUT="/tmp/diff_output_$$.txt"

# NOTE: --exclude matches basenames only (not paths).
# E.g., --exclude='generated' excludes any dir/file named "generated" at any level.
diff -rq \
    --exclude='*.o' \
    --exclude='*.ko' \
    --exclude='*.mod' \
    --exclude='*.mod.c' \
    --exclude='.*.cmd' \
    --exclude='*.cmd' \
    --exclude='*.rej' \
    --exclude='*.orig' \
    --exclude='modules.order' \
    --exclude='Module.symvers' \
    --exclude='.config' \
    --exclude='.config.old' \
    --exclude='vmlinux' \
    --exclude='vmlinux.bin' \
    --exclude='vmlinux.bin.lzma' \
    --exclude='vmlinux.symvers' \
    --exclude='System.map' \
    --exclude='*.img' \
    --exclude='auto.conf' \
    --exclude='auto.conf.cmd' \
    --exclude='tristate.conf' \
    --exclude='*.a' \
    --exclude='built-in.a' \
    --exclude='.tmp_*' \
    --exclude='*.tmp' \
    --exclude='*.dtb' \
    --exclude='vmlinux.lds' \
    --exclude='asm-offsets.s' \
    --exclude='vdso-image.c' \
    --exclude='vdso.lds' \
    --exclude='.version' \
    --exclude='compile.h' \
    --exclude='utsrelease.h' \
    --exclude='bounds.s' \
    --exclude='.missing-syscalls.d' \
    --exclude='.git' \
    --exclude='.gitignore' \
    --exclude='generated' \
    --exclude='config' \
    --exclude='modules.builtin*' \
    --exclude='config_data*' \
    --exclude='crc32table.h' \
    --exclude='*.lex.c' \
    --exclude='*.tab.c' \
    --exclude='*.tab.h' \
    --exclude='fixdep' \
    --exclude='conf' \
    --exclude='modpost' \
    --exclude='dtc' \
    "$VANILLA_DIR" "$PATCHED_DIR" > "$DIFF_OUTPUT" 2>/dev/null || true

# Process the diff output
while IFS= read -r line; do
    # Parse diff output
    # "Only in PATCHED/path: filename" -> new file
    # "Files VANILLA/file and PATCHED/file differ" -> modified file

    if [[ "$line" =~ ^Only\ in\ ${PATCHED_DIR}(.*):[[:space:]](.+)$ ]]; then
        # New file in patched kernel
        subdir="${BASH_REMATCH[1]}"
        filename="${BASH_REMATCH[2]}"
        rel_path="${subdir#/}/$filename"
        rel_path="${rel_path#/}"

        # Skip generated files
        if should_skip "$rel_path"; then
            continue
        fi

        src_file="$PATCHED_DIR$subdir/$filename"

        # Skip binary files
        if file -b "$src_file" 2>/dev/null | grep -qE '^ELF|^PE32|^Mach-O|^PNG|^JPEG|^GIF|^data$'; then
            continue
        fi

        # Handle directories recursively
        if [ -d "$src_file" ]; then
            find "$src_file" -type f | while read -r f; do
                rel="${f#$PATCHED_DIR/}"
                if should_skip "$rel"; then
                    continue
                fi
                if file -b "$f" 2>/dev/null | grep -qE '^ELF|^PE32|^Mach-O|^PNG|^JPEG|^GIF|^data$'; then
                    continue
                fi
                dest_dir="${OUTPUT_FILES}/$(dirname "$rel")"
                mkdir -p "$dest_dir"
                cp "$f" "$dest_dir/"
                echo "  [NEW] $rel"
            done
        else
            dest_dir="${OUTPUT_FILES}${subdir}"
            mkdir -p "$dest_dir"
            cp "$src_file" "$dest_dir/"
            echo "  [NEW] $rel_path"
        fi

    elif [[ "$line" =~ ^Files\ (.+)\ and\ (.+)\ differ$ ]]; then
        # Modified file
        vanilla_file="${BASH_REMATCH[1]}"
        patched_file="${BASH_REMATCH[2]}"

        # Get relative path
        rel_path="${patched_file#$PATCHED_DIR/}"

        # Skip generated files
        if should_skip "$rel_path"; then
            continue
        fi

        # Skip binary files
        if file -b "$patched_file" 2>/dev/null | grep -qE '^ELF|^PE32|^Mach-O|^PNG|^JPEG|^GIF|^data$'; then
            continue
        fi

        # Generate patch filename: a/b/c.h -> a-b-c.h.patch
        patch_name="$(echo "$rel_path" | tr '/' '-').patch"

        # Generate unified diff with relative paths (a/ and b/ prefixes for patch -p1)
        diff -u "$vanilla_file" "$patched_file" | \
            sed "1s|^--- .*|--- a/$rel_path|; 2s|^+++ .*|+++ b/$rel_path|" \
            > "${OUTPUT_PATCHES}/$patch_name" 2>/dev/null || true

        echo "  [MOD] $rel_path"
    fi
done < "$DIFF_OUTPUT"

rm -f "$DIFF_OUTPUT"

# Copy extra files (config, scripts, etc.) from existing files/ if present
ORIGINAL_FILES_DIR="$(dirname "$PATCHED_DIR")/files"
if [ -d "$ORIGINAL_FILES_DIR" ]; then
    echo ""
    echo -e "${YELLOW}Copying extra files from original files/ directory...${NC}"

    # Copy config file if exists
    for f in "$ORIGINAL_FILES_DIR"/config-*.txt; do
        if [ -f "$f" ]; then
            cp "$f" "$OUTPUT_FILES/"
            echo "  [EXTRA] $(basename "$f")"
        fi
    done

    # Copy shell scripts at root of files/
    for f in "$ORIGINAL_FILES_DIR"/*.sh; do
        if [ -f "$f" ]; then
            cp "$f" "$OUTPUT_FILES/"
            echo "  [EXTRA] $(basename "$f")"
        fi
    done
fi

# Count results
NEW_FILES=$(find "$OUTPUT_FILES" -type f 2>/dev/null | wc -l)
MODIFIED_FILES=$(find "$OUTPUT_PATCHES" -name '*.patch' 2>/dev/null | wc -l)

echo ""
echo "==================================================================="
echo "  EXTRACTION COMPLETE"
echo "==================================================================="
echo ""
echo "  New files:      $NEW_FILES (in ${OUTPUT_FILES}/)"
echo "  Modified files: $MODIFIED_FILES (in ${OUTPUT_PATCHES}/)"
echo ""

# Clean up vanilla sources (no longer needed)
rm -rf "$VANILLA_DIR"
rm -f "$KERNEL_TARBALL"

echo -e "${GREEN}Done!${NC}"
